export const actionTypeRap = {
    LAY_THONG_TIN_HE_THONG_RAP : 'LAY_THONG_TIN_HE_THONG_RAP',
    LAY_THONG_TIN_RAP_THEO_HE_THONG : 'LAY_THONG_TIN_RAP_THEO_HE_THONG',
    LAY_DANH_SACH_PHIM_TRONG_RAP : ' LAY_DANH_SACH_PHIM_TRONG_RAP',
    LAY_THONG_TIN_LICH_CHIEU_PHIM : 'LAY_THONG_TIN_LICH_CHIEU_PHIM'
}