export const actionTypePhim = {

    LAY_DANH_SACH_PHIM : 'LAY_DANH_SACH_PHIM',
    LAY_THONG_TIN_PHIM : 'LAY_THONG_TIN_PHIM',
    THEM_PHIM : 'THEM_PHIM',
    XOA_PHIM : 'XOA_PHIM',
    LAY_THONG_TIN_PHIM_CAP_NHAT : 'LAY_THONG_TIN_PHIM_CAP_NHAT',
    LAY_THONG_TIN_RAP :  'LAY_THONG_TIN_RAP',
    LAY_DANH_SACH_PHONG_VE : 'LAY_DANH_SACH_PHONG_VE'

}